from taipy.gui import Gui, Icon
import math
import taipy.gui.builder as tgb
from datetime import date, timedelta


markdown = """
# Generated by *Taipy*

You can insert *Markdown* code in a `text` control to  
add style to the text.

If a line ends with two white spaces, such as here  
then you can create line skips.
"""  # noqa W291
demo={
    'name': ['Alice','Bob','Aisha'],
    'age':[19,20,23]
}
# Biến trạng thái được khai báo
output = "Nhấn nút để bắt đầu!"

icon=Icon("d:/logoNBA.jpg","Nhấn vào đây")

def on_change(state, _, var_value):
    # Update the text controls
    state.start_sel = all_dates[var_value[0]]
    state.end_sel = all_dates[var_value[1]]

# Create the list of dates (all year 2000)
all_dates = {}
all_dates_str = []
start_date = date(2000, 1, 1)
end_date = date(2001, 1, 1)
a_date = start_date
while a_date < end_date:
    date_str = a_date.strftime("%Y/%m/%d")
    all_dates_str.append(date_str)
    all_dates[date_str] = a_date
    a_date += timedelta(days=1)
# Initial selection: first and last day
dates = [all_dates_str[1], all_dates_str[-1]]
# These two variables are used in text controls
start_sel = all_dates[dates[0]]
end_sel = all_dates[dates[1]]
# x values: [-10..10]
x_range = range(-10, 11)
data = {
    "X": x_range,
    "Y": [x*x for x in x_range],
    "Y2": [math.cos(2 * math.pi * x / 10) / 360 for x in x_range]
}

types = [("bar", "Bar"), ("line", "Line")]
selected_type = types[0]

page = """
<|{markdown}|text|mode=markdown|> 
<|Button Label|button|>
<|{icon}|button|on_action=handle_click|>
<|{output}|text|>
<|{demo}|table|> 
<|Error|button|class_name=error|>
<|Secondary|button|class_name=secondary|>
<|{value}|input|>
<br/>
<|{value}|number|min=10|max=60|step=5|>
<br/>
<|{dates}|slider|lov={all_dates_str}|>

Start: <|{start_sel}|text|format=d MMM|>

End: <|{end_sel}|text|format=d MMM|>
<br/>
<|{value}|toggle|lov=Item 1;Item 2;Item 3|unselected_value=No Value|>

<br/>
<|{data}|chart|type={selected_type[0]}|x=X|y=Y|>

<|{selected_type}|toggle|lov={types}|>
"""
# Hàm xử lý sự kiện
def handle_click(state, id, payload):
    state.output = "Bạn đã nhấn nút với icon!"

if __name__ == "__main__":
    print(page)
    Gui(page).run(title="Text - Markdown mode")